name: OMMI_test3
channels:
  - conda-forge
dependencies:
  - python==3.8.10
  - pip
  - numpy>=1.16
  - pyserial
  - tifffile
  - matplotlib
  - scikit-image
  - opencv
  - pip:
    - sti-LabJackPython
    - pyqt5
    - pymmcore


