# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isoi_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 791, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.expSlider = QtWidgets.QSlider(self.tab)
        self.expSlider.setGeometry(QtCore.QRect(540, 10, 160, 19))
        self.expSlider.setOrientation(QtCore.Qt.Horizontal)
        self.expSlider.setObjectName("expSlider")
        self.liveBtn = QtWidgets.QPushButton(self.tab)
        self.liveBtn.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.liveBtn.setObjectName("liveBtn")
        self.cropBtn = QtWidgets.QPushButton(self.tab)
        self.cropBtn.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.cropBtn.setObjectName("cropBtn")
        self.expLabel = QtWidgets.QLabel(self.tab)
        self.expLabel.setGeometry(QtCore.QRect(460, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel.setFont(font)
        self.expLabel.setObjectName("expLabel")
        self.histoBtn = QtWidgets.QPushButton(self.tab)
        self.histoBtn.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.histoBtn.setObjectName("histoBtn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.C_expSb = QtWidgets.QDoubleSpinBox(self.tab)
        self.C_expSb.setGeometry(QtCore.QRect(710, 10, 62, 22))
        self.C_expSb.setObjectName("C_expSb")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Green = QtWidgets.QCheckBox(self.tab)
        self.Green.setGeometry(QtCore.QRect(120, 200, 75, 17))
        self.Green.setObjectName("Green")
        self.Red = QtWidgets.QCheckBox(self.tab)
        self.Red.setGeometry(QtCore.QRect(210, 200, 75, 17))
        self.Red.setObjectName("Red")
        self.BLUE = QtWidgets.QCheckBox(self.tab)
        self.BLUE.setGeometry(QtCore.QRect(280, 200, 75, 17))
        self.BLUE.setObjectName("BLUE")
        self.unloadBtn = QtWidgets.QPushButton(self.tab)
        self.unloadBtn.setGeometry(QtCore.QRect(634, 210, 91, 23))
        self.unloadBtn.setObjectName("unloadBtn")
        self.uncropBtn = QtWidgets.QPushButton(self.tab)
        self.uncropBtn.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.uncropBtn.setObjectName("uncropBtn")
        self.loadBtn = QtWidgets.QPushButton(self.tab)
        self.loadBtn.setGeometry(QtCore.QRect(540, 210, 91, 23))
        self.loadBtn.setObjectName("loadBtn")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(32, 102, 721, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.bitBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bitBox.setObjectName("bitBox")
        self.horizontalLayout.addWidget(self.bitBox)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.binBox = QtWidgets.QComboBox(self.layoutWidget)
        self.binBox.setObjectName("binBox")
        self.horizontalLayout.addWidget(self.binBox)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.shutBox = QtWidgets.QComboBox(self.layoutWidget)
        self.shutBox.setObjectName("shutBox")
        self.horizontalLayout.addWidget(self.shutBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(271, 130, 421, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.triggerBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.triggerBox.setObjectName("triggerBox")
        self.horizontalLayout_2.addWidget(self.triggerBox)
        self.triggerBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.triggerBtn.setObjectName("triggerBtn")
        self.horizontalLayout_2.addWidget(self.triggerBtn)
        self.expLabel_2 = QtWidgets.QLabel(self.tab)
        self.expLabel_2.setGeometry(QtCore.QRect(460, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel_2.setFont(font)
        self.expLabel_2.setObjectName("expLabel_2")
        self.realExp = QtWidgets.QLabel(self.tab)
        self.realExp.setGeometry(QtCore.QRect(580, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.realExp.setFont(font)
        self.realExp.setText("")
        self.realExp.setObjectName("realExp")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.SaveEBtn = QtWidgets.QPushButton(self.tab_2)
        self.SaveEBtn.setGeometry(QtCore.QRect(590, 150, 154, 23))
        self.SaveEBtn.setObjectName("SaveEBtn")
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(560, 210, 225, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 301, 191))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 2)
        self.dur = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.dur.setObjectName("dur")
        self.gridLayout_2.addWidget(self.dur, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.gRatio = QtWidgets.QSpinBox(self.layoutWidget2)
        self.gRatio.setObjectName("gRatio")
        self.gridLayout.addWidget(self.gRatio, 0, 1, 1, 1)
        self.rRatio = QtWidgets.QSpinBox(self.layoutWidget2)
        self.rRatio.setObjectName("rRatio")
        self.gridLayout.addWidget(self.rRatio, 1, 1, 1, 1)
        self.bRatio = QtWidgets.QSpinBox(self.layoutWidget2)
        self.bRatio.setObjectName("bRatio")
        self.gridLayout.addWidget(self.bRatio, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 2)
        self.abortBtn = QtWidgets.QPushButton(self.tab_2)
        self.abortBtn.setGeometry(QtCore.QRect(590, 180, 154, 23))
        self.abortBtn.setObjectName("abortBtn")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(560, 30, 211, 46))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.fileSize = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.fileSize.setObjectName("fileSize")
        self.gridLayout_3.addWidget(self.fileSize, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.framesPerFileLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.framesPerFileLabel.setObjectName("framesPerFileLabel")
        self.gridLayout_3.addWidget(self.framesPerFileLabel, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(338, 20, 96, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.intervalMs = QtWidgets.QSpinBox(self.tab_2)
        self.intervalMs.setGeometry(QtCore.QRect(440, 20, 95, 20))
        self.intervalMs.setObjectName("intervalMs")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ISOI Software"))
        self.liveBtn.setText(_translate("MainWindow", "LIVE"))
        self.cropBtn.setText(_translate("MainWindow", "Crop"))
        self.expLabel.setText(_translate("MainWindow", "Exposure :"))
        self.histoBtn.setText(_translate("MainWindow", "Histogram"))
        self.label.setText(_translate("MainWindow", "Camera settings"))
        self.label_2.setText(_translate("MainWindow", "LEDs"))
        self.Green.setText(_translate("MainWindow", "GREEN"))
        self.Red.setText(_translate("MainWindow", "RED"))
        self.BLUE.setText(_translate("MainWindow", "BLUE"))
        self.unloadBtn.setText(_translate("MainWindow", "Unload devices"))
        self.uncropBtn.setText(_translate("MainWindow", "Uncrop"))
        self.loadBtn.setText(_translate("MainWindow", "load devices"))
        self.label_7.setText(_translate("MainWindow", "Bit depth :"))
        self.label_3.setText(_translate("MainWindow", "Binning :"))
        self.label_13.setText(_translate("MainWindow", "Shutter mode :"))
        self.label_14.setText(_translate("MainWindow", "Trigger mode :"))
        self.triggerBtn.setText(_translate("MainWindow", "Snap (ext trig)"))
        self.expLabel_2.setText(_translate("MainWindow", "Real exposure :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Control"))
        self.SaveEBtn.setText(_translate("MainWindow", "RUN AND SAVE"))
        self.label_11.setText(_translate("MainWindow", "Name :"))
        self.label_4.setText(_translate("MainWindow", "Duration (s) :"))
        self.label_5.setText(_translate("MainWindow", "LEDs ratio :"))
        self.label_6.setText(_translate("MainWindow", "Green"))
        self.label_8.setText(_translate("MainWindow", "Red"))
        self.label_9.setText(_translate("MainWindow", "Blue"))
        self.abortBtn.setText(_translate("MainWindow", "ABORT"))
        self.label_12.setText(_translate("MainWindow", "Max file size (GB) :"))
        self.label_10.setText(_translate("MainWindow", "Frames per file :"))
        self.framesPerFileLabel.setText(_translate("MainWindow", "5787"))
        self.label_15.setText(_translate("MainWindow", "Interval (ms)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Run and Save"))

