# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isoi_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 64, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.expSlider = QtWidgets.QSlider(self.tab)
        self.expSlider.setGeometry(QtCore.QRect(400, 50, 160, 19))
        self.expSlider.setOrientation(QtCore.Qt.Horizontal)
        self.expSlider.setObjectName("expSlider")
        self.bitBox = QtWidgets.QComboBox(self.tab)
        self.bitBox.setGeometry(QtCore.QRect(290, 102, 69, 20))
        self.bitBox.setObjectName("bitBox")
        self.liveBtn = QtWidgets.QPushButton(self.tab)
        self.liveBtn.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.liveBtn.setObjectName("liveBtn")
        self.cropBtn = QtWidgets.QPushButton(self.tab)
        self.cropBtn.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.cropBtn.setObjectName("cropBtn")
        self.expLabel = QtWidgets.QLabel(self.tab)
        self.expLabel.setGeometry(QtCore.QRect(320, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel.setFont(font)
        self.expLabel.setObjectName("expLabel")
        self.binBox = QtWidgets.QComboBox(self.tab)
        self.binBox.setGeometry(QtCore.QRect(100, 104, 69, 20))
        self.binBox.setObjectName("binBox")
        self.histoBtn = QtWidgets.QPushButton(self.tab)
        self.histoBtn.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.histoBtn.setObjectName("histoBtn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(210, 100, 74, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.C_expSb = QtWidgets.QDoubleSpinBox(self.tab)
        self.C_expSb.setGeometry(QtCore.QRect(570, 50, 62, 22))
        self.C_expSb.setObjectName("C_expSb")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Green = QtWidgets.QCheckBox(self.tab)
        self.Green.setGeometry(QtCore.QRect(120, 200, 75, 17))
        self.Green.setObjectName("Green")
        self.Red = QtWidgets.QCheckBox(self.tab)
        self.Red.setGeometry(QtCore.QRect(210, 200, 75, 17))
        self.Red.setObjectName("Red")
        self.BLUE = QtWidgets.QCheckBox(self.tab)
        self.BLUE.setGeometry(QtCore.QRect(280, 200, 75, 17))
        self.BLUE.setObjectName("BLUE")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.SaveEBtn = QtWidgets.QPushButton(self.tab_2)
        self.SaveEBtn.setGeometry(QtCore.QRect(270, 70, 154, 23))
        self.SaveEBtn.setObjectName("SaveEBtn")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ISOI Software"))
        self.label_3.setText(_translate("MainWindow", "Binning :"))
        self.liveBtn.setText(_translate("MainWindow", "LIVE"))
        self.cropBtn.setText(_translate("MainWindow", "Crop"))
        self.expLabel.setText(_translate("MainWindow", "Exposure :"))
        self.histoBtn.setText(_translate("MainWindow", "Histogram"))
        self.label.setText(_translate("MainWindow", "Camera settings"))
        self.label_7.setText(_translate("MainWindow", "Bit depth :"))
        self.label_2.setText(_translate("MainWindow", "LEDs"))
        self.Green.setText(_translate("MainWindow", "GREEN"))
        self.Red.setText(_translate("MainWindow", "RED"))
        self.BLUE.setText(_translate("MainWindow", "BLUE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Control"))
        self.SaveEBtn.setText(_translate("MainWindow", "SAVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Run and Save"))

