# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'isoi_window_V2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 861, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(32, 192, 721, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.bitBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bitBox.setObjectName("bitBox")
        self.horizontalLayout.addWidget(self.bitBox)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.binBox = QtWidgets.QComboBox(self.layoutWidget)
        self.binBox.setObjectName("binBox")
        self.horizontalLayout.addWidget(self.binBox)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.shutBox = QtWidgets.QComboBox(self.layoutWidget)
        self.shutBox.setObjectName("shutBox")
        self.horizontalLayout.addWidget(self.shutBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 220, 484, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.triggerBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.triggerBox.setObjectName("triggerBox")
        self.horizontalLayout_2.addWidget(self.triggerBox)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.overlapBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.overlapBox.setObjectName("overlapBox")
        self.horizontalLayout_2.addWidget(self.overlapBox)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(30, 320, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(420, 270, 261, 24))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.expRatio = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.expRatio.setObjectName("expRatio")
        self.horizontalLayout_7.addWidget(self.expRatio)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 50, 281, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.expLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel.setFont(font)
        self.expLabel.setObjectName("expLabel")
        self.gridLayout_4.addWidget(self.expLabel, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.expSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.expSlider.setOrientation(QtCore.Qt.Horizontal)
        self.expSlider.setObjectName("expSlider")
        self.horizontalLayout_4.addWidget(self.expSlider)
        self.C_expSb = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.C_expSb.setObjectName("C_expSb")
        self.horizontalLayout_4.addWidget(self.C_expSb)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 1, 1, 2)
        self.expLabel_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel_2.setFont(font)
        self.expLabel_2.setObjectName("expLabel_2")
        self.gridLayout_4.addWidget(self.expLabel_2, 1, 0, 1, 2)
        self.realExp = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.realExp.setFont(font)
        self.realExp.setText("")
        self.realExp.setObjectName("realExp")
        self.gridLayout_4.addWidget(self.realExp, 1, 2, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 260, 321, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.Green = QtWidgets.QCheckBox(self.layoutWidget3)
        self.Green.setObjectName("Green")
        self.horizontalLayout_6.addWidget(self.Green)
        self.Red = QtWidgets.QCheckBox(self.layoutWidget3)
        self.Red.setObjectName("Red")
        self.horizontalLayout_6.addWidget(self.Red)
        self.Blue = QtWidgets.QCheckBox(self.layoutWidget3)
        self.Blue.setObjectName("Blue")
        self.horizontalLayout_6.addWidget(self.Blue)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(560, 370, 215, 191))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.fileSize = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.fileSize.setObjectName("fileSize")
        self.gridLayout_3.addWidget(self.fileSize, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.framesPerFileLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.framesPerFileLabel.setObjectName("framesPerFileLabel")
        self.gridLayout_3.addWidget(self.framesPerFileLabel, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.ledTrigBox = QtWidgets.QComboBox(self.layoutWidget4)
        self.ledTrigBox.setObjectName("ledTrigBox")
        self.horizontalLayout_3.addWidget(self.ledTrigBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.arduinoBtn = QtWidgets.QPushButton(self.layoutWidget4)
        self.arduinoBtn.setObjectName("arduinoBtn")
        self.verticalLayout.addWidget(self.arduinoBtn)
        self.runSaveBtn = QtWidgets.QPushButton(self.layoutWidget4)
        self.runSaveBtn.setObjectName("runSaveBtn")
        self.verticalLayout.addWidget(self.runSaveBtn)
        self.abortBtn = QtWidgets.QPushButton(self.layoutWidget4)
        self.abortBtn.setObjectName("abortBtn")
        self.verticalLayout.addWidget(self.abortBtn)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 120, 281, 60))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.expLabel_3 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expLabel_3.setFont(font)
        self.expLabel_3.setObjectName("expLabel_3")
        self.horizontalLayout_11.addWidget(self.expLabel_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.approxFramerateLabel = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.approxFramerateLabel.setFont(font)
        self.approxFramerateLabel.setObjectName("approxFramerateLabel")
        self.horizontalLayout_8.addWidget(self.approxFramerateLabel)
        self.approxFramerateBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.approxFramerateBtn.setObjectName("approxFramerateBtn")
        self.horizontalLayout_8.addWidget(self.approxFramerateBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.testFramerateLabel = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.testFramerateLabel.setFont(font)
        self.testFramerateLabel.setObjectName("testFramerateLabel")
        self.horizontalLayout_10.addWidget(self.testFramerateLabel)
        self.testFramerateBtn = QtWidgets.QPushButton(self.layoutWidget5)
        self.testFramerateBtn.setObjectName("testFramerateBtn")
        self.horizontalLayout_10.addWidget(self.testFramerateBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.layoutWidget6 = QtWidgets.QWidget(self.tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(340, 51, 171, 71))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.histoBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.histoBtn.setObjectName("histoBtn")
        self.gridLayout_5.addWidget(self.histoBtn, 0, 0, 1, 1)
        self.cropBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.cropBtn.setObjectName("cropBtn")
        self.gridLayout_5.addWidget(self.cropBtn, 0, 1, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout_5.addWidget(self.loadBtn, 1, 0, 1, 1)
        self.unloadBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.unloadBtn.setObjectName("unloadBtn")
        self.gridLayout_5.addWidget(self.unloadBtn, 1, 1, 1, 1)
        self.layoutWidget7 = QtWidgets.QWidget(self.tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(542, 50, 261, 54))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.loadSettingsBtn = QtWidgets.QPushButton(self.layoutWidget7)
        self.loadSettingsBtn.setObjectName("loadSettingsBtn")
        self.gridLayout_2.addWidget(self.loadSettingsBtn, 0, 1, 1, 1)
        self.settingsFileName = QtWidgets.QLineEdit(self.layoutWidget7)
        self.settingsFileName.setObjectName("settingsFileName")
        self.gridLayout_2.addWidget(self.settingsFileName, 1, 0, 1, 1)
        self.selectSettingsFileBtn = QtWidgets.QPushButton(self.layoutWidget7)
        self.selectSettingsFileBtn.setObjectName("selectSettingsFileBtn")
        self.gridLayout_2.addWidget(self.selectSettingsFileBtn, 1, 1, 1, 1)
        self.layoutWidget8 = QtWidgets.QWidget(self.tab)
        self.layoutWidget8.setGeometry(QtCore.QRect(30, 353, 421, 25))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.savingPath = QtWidgets.QLineEdit(self.layoutWidget8)
        self.savingPath.setObjectName("savingPath")
        self.horizontalLayout_5.addWidget(self.savingPath)
        self.savingPathBtn = QtWidgets.QPushButton(self.layoutWidget8)
        self.savingPathBtn.setObjectName("savingPathBtn")
        self.horizontalLayout_5.addWidget(self.savingPathBtn)
        self.layoutWidget9 = QtWidgets.QWidget(self.tab)
        self.layoutWidget9.setGeometry(QtCore.QRect(30, 379, 421, 22))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.experimentName = QtWidgets.QLineEdit(self.layoutWidget9)
        self.experimentName.setObjectName("experimentName")
        self.horizontalLayout_12.addWidget(self.experimentName)
        self.layoutWidget10 = QtWidgets.QWidget(self.tab)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 410, 421, 131))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.experimentDuration = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.experimentDuration.setObjectName("experimentDuration")
        self.gridLayout_6.addWidget(self.experimentDuration, 0, 1, 1, 1)
        self.rgbMode = QtWidgets.QCheckBox(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rgbMode.setFont(font)
        self.rgbMode.setObjectName("rgbMode")
        self.gridLayout_6.addWidget(self.rgbMode, 1, 0, 1, 3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.gRatio = QtWidgets.QSpinBox(self.layoutWidget10)
        self.gRatio.setObjectName("gRatio")
        self.gridLayout.addWidget(self.gRatio, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.rRatio = QtWidgets.QSpinBox(self.layoutWidget10)
        self.rRatio.setObjectName("rRatio")
        self.gridLayout.addWidget(self.rRatio, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.bRatio = QtWidgets.QSpinBox(self.layoutWidget10)
        self.bRatio.setObjectName("bRatio")
        self.gridLayout.addWidget(self.bRatio, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 1, 3, 1, 1)
        self.rbMode = QtWidgets.QCheckBox(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rbMode.setFont(font)
        self.rbMode.setObjectName("rbMode")
        self.gridLayout_6.addWidget(self.rbMode, 2, 0, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.gNbFrames = QtWidgets.QSpinBox(self.layoutWidget10)
        self.gNbFrames.setProperty("value", 1)
        self.gNbFrames.setObjectName("gNbFrames")
        self.horizontalLayout_9.addWidget(self.gNbFrames)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.gInterval = QtWidgets.QSpinBox(self.layoutWidget10)
        self.gInterval.setMaximum(10000)
        self.gInterval.setObjectName("gInterval")
        self.horizontalLayout_9.addWidget(self.gInterval)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 2, 2, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ISOI Software"))
        self.label.setText(_translate("MainWindow", "Camera settings"))
        self.label_7.setText(_translate("MainWindow", "Bit depth :"))
        self.label_3.setText(_translate("MainWindow", "Binning :"))
        self.label_13.setText(_translate("MainWindow", "Shutter mode :"))
        self.label_14.setText(_translate("MainWindow", "Trigger mode :"))
        self.label_18.setText(_translate("MainWindow", "Overlap :"))
        self.label_17.setText(_translate("MainWindow", "Acquisition settings"))
        self.label_15.setText(_translate("MainWindow", "Interval LED ON (%exp)"))
        self.expLabel.setText(_translate("MainWindow", "Exposure :"))
        self.expLabel_2.setText(_translate("MainWindow", "Real exposure :"))
        self.label_2.setText(_translate("MainWindow", "LEDs"))
        self.Green.setText(_translate("MainWindow", "GREEN"))
        self.Red.setText(_translate("MainWindow", "RED"))
        self.Blue.setText(_translate("MainWindow", "BLUE"))
        self.label_12.setText(_translate("MainWindow", "Max file size (GB) :"))
        self.label_10.setText(_translate("MainWindow", "Frames per file :"))
        self.framesPerFileLabel.setText(_translate("MainWindow", "5787"))
        self.label_16.setText(_translate("MainWindow", "LED trigger mode :"))
        self.arduinoBtn.setText(_translate("MainWindow", "ARDUINO SYNC"))
        self.runSaveBtn.setText(_translate("MainWindow", "RUN AND SAVE"))
        self.abortBtn.setText(_translate("MainWindow", "ABORT"))
        self.expLabel_3.setText(_translate("MainWindow", "Framerate :"))
        self.approxFramerateLabel.setText(_translate("MainWindow", "press btn"))
        self.approxFramerateBtn.setText(_translate("MainWindow", "Approx Framerate"))
        self.testFramerateLabel.setText(_translate("MainWindow", "press btn"))
        self.testFramerateBtn.setText(_translate("MainWindow", "Test Framerate"))
        self.histoBtn.setText(_translate("MainWindow", "Live Histogram"))
        self.cropBtn.setText(_translate("MainWindow", "Crop"))
        self.loadBtn.setText(_translate("MainWindow", "load Zyla"))
        self.unloadBtn.setText(_translate("MainWindow", "Unload Zyla"))
        self.label_5.setText(_translate("MainWindow", "Load settings :"))
        self.loadSettingsBtn.setText(_translate("MainWindow", "Load"))
        self.selectSettingsFileBtn.setText(_translate("MainWindow", "Browse..."))
        self.label_19.setText(_translate("MainWindow", "Saving folder :"))
        self.savingPathBtn.setText(_translate("MainWindow", "Browse..."))
        self.label_11.setText(_translate("MainWindow", "Name :"))
        self.label_4.setText(_translate("MainWindow", "Duration (s) :"))
        self.rgbMode.setText(_translate("MainWindow", "Red-Green-Blue mode :"))
        self.label_6.setText(_translate("MainWindow", "Green"))
        self.label_8.setText(_translate("MainWindow", "Red"))
        self.label_9.setText(_translate("MainWindow", "Blue"))
        self.rbMode.setText(_translate("MainWindow", "Red-Blue mode :"))
        self.label_20.setText(_translate("MainWindow", "Green"))
        self.label_21.setText(_translate("MainWindow", "each (nb frames) :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Run and Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Images Analysis"))

