# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OII_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 275)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 711, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.layoutWidget = QtWidgets.QWidget(self.control)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.SnapBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.SnapBtn.setObjectName("SnapBtn")
        self.gridLayout.addWidget(self.SnapBtn, 1, 0, 1, 1)
        self.C_expSb = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.C_expSb.setObjectName("C_expSb")
        self.gridLayout.addWidget(self.C_expSb, 0, 4, 1, 1)
        self.expSlider = QtWidgets.QSlider(self.layoutWidget)
        self.expSlider.setMaximum(99)
        self.expSlider.setOrientation(QtCore.Qt.Horizontal)
        self.expSlider.setObjectName("expSlider")
        self.gridLayout.addWidget(self.expSlider, 0, 3, 1, 1)
        self.LiveBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.LiveBtn.setObjectName("LiveBtn")
        self.gridLayout.addWidget(self.LiveBtn, 0, 0, 1, 1)
        self.Green = QtWidgets.QCheckBox(self.layoutWidget)
        self.Green.setObjectName("Green")
        self.gridLayout.addWidget(self.Green, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 2, 1)
        self.binBox = QtWidgets.QComboBox(self.layoutWidget)
        self.binBox.setObjectName("binBox")
        self.gridLayout.addWidget(self.binBox, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        self.Valve2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.Valve2.setObjectName("Valve2")
        self.gridLayout.addWidget(self.Valve2, 3, 2, 1, 1)
        self.Red = QtWidgets.QCheckBox(self.layoutWidget)
        self.Red.setObjectName("Red")
        self.gridLayout.addWidget(self.Red, 3, 1, 1, 1)
        self.bitBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bitBox.setObjectName("bitBox")
        self.gridLayout.addWidget(self.bitBox, 3, 4, 1, 1)
        self.Valve1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.Valve1.setObjectName("Valve1")
        self.gridLayout.addWidget(self.Valve1, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.path = QtWidgets.QLineEdit(self.layoutWidget)
        self.path.setObjectName("path")
        self.gridLayout.addWidget(self.path, 1, 3, 1, 1)
        self.histoBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.histoBtn.setObjectName("histoBtn")
        self.gridLayout.addWidget(self.histoBtn, 0, 1, 1, 1)
        self.CropBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.CropBtn.setObjectName("CropBtn")
        self.gridLayout.addWidget(self.CropBtn, 1, 1, 1, 1)
        self.tabWidget.addTab(self.control, "")
        self.epoch = QtWidgets.QWidget()
        self.epoch.setObjectName("epoch")
        self.layoutWidget1 = QtWidgets.QWidget(self.epoch)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 691, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.odo = QtWidgets.QSpinBox(self.layoutWidget1)
        self.odo.setObjectName("odo")
        self.gridLayout_2.addWidget(self.odo, 6, 4, 1, 2)
        self.LoadEBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.LoadEBtn.setObjectName("LoadEBtn")
        self.gridLayout_2.addWidget(self.LoadEBtn, 0, 4, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 3)
        self.listE = QtWidgets.QListWidget(self.layoutWidget1)
        self.listE.setObjectName("listE")
        self.gridLayout_2.addWidget(self.listE, 0, 7, 7, 1)
        self.RemBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.RemBtn.setObjectName("RemBtn")
        self.gridLayout_2.addWidget(self.RemBtn, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 4, 1, 1)
        self.E_expSb = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.E_expSb.setObjectName("E_expSb")
        self.gridLayout_2.addWidget(self.E_expSb, 2, 5, 1, 1)
        self.AddBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.AddBtn.setObjectName("AddBtn")
        self.gridLayout_2.addWidget(self.AddBtn, 0, 0, 1, 2)
        self.led = QtWidgets.QSpinBox(self.layoutWidget1)
        self.led.setObjectName("led")
        self.gridLayout_2.addWidget(self.led, 4, 4, 1, 2)
        self.SaveEBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.SaveEBtn.setObjectName("SaveEBtn")
        self.gridLayout_2.addWidget(self.SaveEBtn, 1, 4, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.repeat = QtWidgets.QSpinBox(self.layoutWidget1)
        self.repeat.setObjectName("repeat")
        self.gridLayout_2.addWidget(self.repeat, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 4)
        self.AbortBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.AbortBtn.setObjectName("AbortBtn")
        self.gridLayout_2.addWidget(self.AbortBtn, 8, 2, 1, 5)
        self.dur = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dur.setObjectName("dur")
        self.gridLayout_2.addWidget(self.dur, 5, 4, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 8, 7, 1, 1)
        self.RunBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.RunBtn.setObjectName("RunBtn")
        self.gridLayout_2.addWidget(self.RunBtn, 8, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 0, 1, 1)
        self.dur_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dur_2.setObjectName("dur_2")
        self.gridLayout_2.addWidget(self.dur_2, 7, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 4, 1, 1)
        self.rec = QtWidgets.QSpinBox(self.layoutWidget1)
        self.rec.setObjectName("rec")
        self.gridLayout_2.addWidget(self.rec, 7, 5, 1, 1)
        self.tabWidget.addTab(self.epoch, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 591, 191))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.comment = QtWidgets.QTextEdit(self.layoutWidget2)
        self.comment.setObjectName("comment")
        self.gridLayout_3.addWidget(self.comment, 0, 1, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intrinsic Imaging"))
        self.SnapBtn.setText(_translate("MainWindow", "SNAP"))
        self.LiveBtn.setText(_translate("MainWindow", "LIVE"))
        self.Green.setText(_translate("MainWindow", "GREEN"))
        self.label.setText(_translate("MainWindow", "LEDs\n"
"&Valves"))
        self.label_3.setText(_translate("MainWindow", "Binning :"))
        self.Valve2.setText(_translate("MainWindow", "valve2"))
        self.Red.setText(_translate("MainWindow", "RED"))
        self.Valve1.setText(_translate("MainWindow", "valve1"))
        self.label_7.setText(_translate("MainWindow", "Bit depth :"))
        self.label_2.setText(_translate("MainWindow", "EXPOSURE :"))
        self.label_8.setText(_translate("MainWindow", "Name :"))
        self.histoBtn.setText(_translate("MainWindow", "histogram"))
        self.CropBtn.setText(_translate("MainWindow", "CROP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control), _translate("MainWindow", "Control"))
        self.LoadEBtn.setText(_translate("MainWindow", "LOAD"))
        self.label_6.setText(_translate("MainWindow", "LED (0:None, 1:green, 2:red) :"))
        self.RemBtn.setText(_translate("MainWindow", "REMOVE"))
        self.label_4.setText(_translate("MainWindow", "Duration (s) :"))
        self.label_10.setText(_translate("MainWindow", "Exp. :"))
        self.AddBtn.setText(_translate("MainWindow", "ADD"))
        self.SaveEBtn.setText(_translate("MainWindow", "SAVE"))
        self.label_11.setText(_translate("MainWindow", "Name :"))
        self.label_12.setText(_translate("MainWindow", "Repeat :"))
        self.label_5.setText(_translate("MainWindow", "Odor (0, 1 or 2) :"))
        self.AbortBtn.setText(_translate("MainWindow", "ABORT"))
        self.RunBtn.setText(_translate("MainWindow", "RUN"))
        self.label_13.setText(_translate("MainWindow", "inter-trials Duration (s) :"))
        self.label_14.setText(_translate("MainWindow", "noRec (0/1) :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.epoch), _translate("MainWindow", "Epochs and Run"))
        self.label_9.setText(_translate("MainWindow", "Comment :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Comment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

